name = "ancientpath-backend"
main = "./index.ts"
compatibility_date = "2023-10-30"

routes = [
  { pattern = "api.ancientpath.dpdns.org", custom_domain = true, zone_name = "ancientpath.dpdns.org" }
]

[[d1_databases]]
binding = "DB"
database_name = "lumina-blog-db"
database_id = "ceb06d47-9d5e-4c5c-a18c-595bc69d4981" 

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "lumina-blog-media"
preview_bucket_name = "lumina-blog-media"

# 允许跨域访问
[vars]
# 填写您刚才开启的公开访问网址，必须带 https://
# 例如: https://pub-123456.r2.dev 或 https://media.yourdomain.com
R2_PUBLIC_DOMAIN = "https://media.ancientpath.dpdns.org" 
# AUTH_SECRET = "" # 敏感信息请在 Cloudflare Dashboard 设置或使用 .dev.vars
# CUSTOM_LLM_API_KEY = ""
# CUSTOM_LLM_API_BASE = ""
# CUSTOM_LLM_MODEL = ""
